### ISSUE TITLE
Tutorial: How to write a Tutorial ...

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#247]
* [ ] Layout and style
  * [ ] Examples to look at
* [ ] Bounties

Cf the #234 (developer guide)

See also https://www.digitalocean.com/community/get-paid-to-write

**Comment by danfowler** [comment]
Not sure there's anything specific to Frictionless Data the way this issue is written, but the original intention as I recall was to provide a way to onboard people wanting to contribute to the project.  

Users with a basic familiarity of Data Packages could contribute tutorials in their language or platform of choice.

This is fine idea but seems somewhat low priority at this point.  It will ultimately be driven by how people actually use the tools.  I move to close.

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#42
