### ISSUE TITLE
User stories from IDW

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/project#304]

**Comment by danfowler** [comment]
Here are user stories I gathered over the course of [International Data Week](http://blog.okfn.org/2016/10/11/international-data-week-from-big-data-to-open-data/):

- [Controlled Vocabularies](https://trello.com/c/U2yfJOHj/32-as-a-researcher-i-want-to-be-able-to-reference-a-remote-controlled-vocabulary-for-my-dataset-so-that-i-can-be-sure-that-column-s)
- [SPSS Integration](https://trello.com/c/XlHZI7um/75-as-a-developer-working-with-data-packages-i-want-an-spss-integration-so-i-can-integrate-data-packaged-data-with-pipelines-that-u)
  - As a researcher, I want to publish a "codebook" as a Data Package so that it is machine-readable
  - As a researcher, I want to publish SPSS data in a non-proprietary format (as a Data Package) so that I be in alignment with my organization's data management plan
- [HDF5/NetCDF4 Integration](https://trello.com/c/7svjoqdA/94-as-a-researcher-working-with-data-in-netcdf-i-want-netcdf-integration-so-that-i-can-store-my-data-in-plaintext-while-still-retai)
- [Excel](https://trello.com/c/wOCROr2a/100-as-a-researcher-i-want-to-get-my-excel-spreadsheet-into-a-data-package-so-that-i-can-benefit-from-better-tooling-and-standardiza)
- ["Matchmaking service"](https://trello.com/c/uVXG3TPD/101-as-a-publisher-i-want-an-app-that-acts-as-a-match-making-service-for-packaging-e-g-biodiversity-data-so-that-data-seekers-are-pa)
- [Integration with Mendeley Data](https://trello.com/c/pdKQBStU/102-as-a-researcher-i-want-an-integration-with-https-data-mendeley-com-so-that-i-can-validate-my-data-upon-ingest-to-the-service)
